# -*- coding: utf-8 -*-
"""dataframe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyJNGbyttdD_4fxY9da9UH3VuLN3-wX-
"""

import pandas as pd
import numpy as np

data_students ={
    'studentID': [101, 102, 103, 104, 105],
    'Name':['alice', 'bob', 'eve', np.nan, np.nan],
    'Age':[20, 22, 21, 24, np.nan],
    'city':['ktm', 'pokhara', np.nan, np.nan, np.nan]
}
df_students = pd.DataFrame(data_students)

data_grades = {
    'studentID': [101, 102, 103, 104, 105],
    'course': ['math', 'math', 'science', 'math', np.nan],
    'score':[85, 92, 78, np.nan, 95]
}
df_grades = pd.DataFrame(data_grades)

df_students.head()

df_grades.head()

median_score = df_grades['score'].median()
df_grades['score'] = df_grades['score'].fillna(median_score)

merged_df = pd.merge(df_students, df_grades, on=['studentID', 'studentID'], how='right')
merged_df

